export const pozScenarios = [
  { t: "Zgłaszam pożar mieszkania na 3 piętrze. Z okien wydobywa się gęsty, czarny dym, a na balkonie stoi kobieta wzywająca pomocy. Dym odciął jej drogę ucieczki.", k: "Na miejscu zdarzenia. Potwierdzam rozwinięty pożar mieszkania na 3 piętrze. Przystępujemy do sprawienia SD-30 celem ewakuacji osoby z balkonu. Rota 1 wprowadzona do natarcia wewnętrznego z linią wężową W-52. Proszę o zadysponowanie ZRM oraz Pogotowia Energetycznego.", locType: "apartment", zrm: true, pol: true },
  { t: "Pali się altanka na terenach ogródków działkowych. Ogień jest bardzo silny i zaczyna przerzucać się na sąsiednie, wysokie drzewa iglaste.", k: "Zlokalizowano pożar altany drewnianej, konstrukcja w całości objęta ogniem. Brak osób poszkodowanych. Podajemy dwa prądy wody w natarciu i jeden w obronie na drzewostan. Teren bardzo trudnodostępny dla GCBA.", locType: "plot" },
  { t: "W trakcie jazdy spod maski samochodu osobowego zaczął wydobywać się siwy dym, a po chwili pojawiły się płomienie. Samochód stoi na poboczu drogi.", k: "Pożar komory silnika samochodu osobowego. Pożar zlokalizowany, podano jeden prąd piany ciężkiej z szybkiego natarcia. Proszę o zadysponowanie patrolu WRD Policji w celu zabezpieczenia pasa ruchu.", locType: "road", pol: true },
  { t: "Zgłaszam zapalenie się sadzy w kominie domu jednorodzinnego. Z komina bucha ogień i sypią się iskry, słychać też bardzo głośny, dudniący dźwięk.", k: "Potwierdzam pożar sadzy w przewodzie kominowym. Wygaszono piec CO. Rozstawiono sprzęt kominiarski (sito i wycior), monitorujemy przewód kamerą termowizyjną. Brak pęknięć na przewodzie, brak stężenia tlenku węgla w pomieszczeniach.", locType: "building" },
  { t: "Ktoś podpalił duże nieużytki przy lesie. Bardzo szybko rozprzestrzeniający się ogień z powodu silnego wiatru. Ściana ognia idzie w stronę zabudowań i lasu.", k: "Ogromny pożar traw na nieużytkach o powierzchni ok. 2 hektarów. Ze względu na silny wiatr pożar szybko się rozwija. Zadysponujcie pilnie 3 dodatkowe zastępy GBA w celu zbudowania linii obrony przed lasem i domami.", locType: "forest" },
  { t: "Automatyczne zgłoszenie z formatki SSP (System Sygnalizacji Pożaru). Obiekt: Hala produkcyjna. Pracownicy ewakuują się ze strefy.", k: "Rozpoznanie potwierdza zadymienie na hali produkcyjnej - pożar maszyny prasującej. Ewakuacja przebiegła sprawnie (120 osób). Wprowadzam dwie roty z ODO do wewnątrz. Potrzebne wsparcie w wentylacji - prosimy o wentylator osiowy dużej wydajności.", locType: "industrial" },
  { t: "Płonie wiata śmietnikowa z kilkoma dużymi kontenerami na plastik i papier na osiedlu wielkiej płyty.", k: "Ugaszono pożar wiaty śmietnikowej podając jeden prąd wody z linii szybkiego natarcia. Zniszczeniu uległy trzy kontenery 1100l. Sytuacja opanowana, brak osób poszkodowanych, brak zagrożenia dla pobliskich zaparkowanych aut.", locType: "building" },
  { t: "Silny wybuch w starej kamienicy. Zawaliła się część ściany frontowej, z gruzowiska wydobywa się ogień. Prawdopodobnie wybuch butli z gazem propan-butan.", k: "Na miejscu katastrofa budowlana! Zniszczona ściana nośna budynku. Kilka osób pod gruzami, widoczne otwarte zarzewia ognia. Pilnie dysponuj na miejsce SGPR, 4 ZRM, LPR, Policję i Pogotowie Gazowe! Odcinam przyłącza mediów.", locType: "building", zrm: true, pol: true },
  { t: "Dym wydobywa się przez zamknięte drzwi z mieszkania sąsiada, który ma problemy z poruszaniem się. Nikt nie otwiera.", k: "Wymuszono wejście sprzętem burzącym (wyważarka hydrauliczna). Wewnątrz ogromne zadymienie od pozostawionego garnka na kuchence. W kuchni ewakuowano 1 nieprzytomną osobę - rozpoczęto tlenoterapię czynną. Przekazujemy pacjenta do ZRM.", locType: "apartment", zrm: true },
  { t: "Zgłoszenie z zakładu obróbki drewna. Potężny pożar magazynu gotowych elementów drewnianych. Płomienie wychodzą już przez uszkodzony dach hali.", k: "Zastano pożar hali produkcyjnej w fazie pełnego rozwoju. Konstrukcja stalowa dachu grozi zawaleniem. Przechodzimy do obrony sąsiednich budynków biurowych. Zażądano zadysponowania plutonu gaśniczego oraz SGRChem ze względu na składowisko lakierów.", locType: "industrial" },
  { t: "Pali się opona i naczepa samochodu ciężarowego przewożącego elektronikę. Pojazd znajduje się na pasie awaryjnym autostrady.", k: "Pożar ugaszony przy użyciu dwóch prądów piany ciężkiej. Opona i część plandeki spalone, ładunek zdołano uratować. Prawy pas jezdni oraz pas awaryjny wyłączone z ruchu przez patrol Policji.", locType: "road", pol: true },
  { t: "Słychać strzelanie przypominające petardy, a po chwili zauważyłem pożar skrzynki elektrycznej i kabli na klatce schodowej wielorodzinnego budynku.", k: "Zlokalizowano zwarcie instalacji elektrycznej w skrzynce rozdzielczej na parterze. Klatka schodowa mocno zadymiona - nakazano mieszkańcom uszczelnienie drzwi i pozostanie w mieszkaniach. Czekamy na Pogotowie Energetyczne.", locType: "apartment" },
  { t: "Dym wydobywa się z podziemnego garażu centrum handlowego. Załączyły się spryskiwacze, ewakuacja w toku.", k: "Potwierdzony pożar dwóch pojazdów na poziomie -2. Temperatura i zadymienie są krytyczne. Roty w natarciu ubezpieczane. Instalacja tryskaczowa (SUG) uruchomiona prawidłowo. Konieczne wsparcie wentylacyjne oddymiania.", locType: "commercial" },
  { t: "Stóg słomy na polu stanął w płomieniach. Prawdopodobnie podpalenie przez młodzież.", k: "Objęty w całości duży stóg słomy. Brak zagrożenia dla upraw i mienia. Kontrolujemy proces dopalania, przerzucamy słomę przy pomocy ciągnika rolniczego i wideł.", locType: "forest" },
  { t: "Na terenie budowy doszło do zapłonu pojemników z lepikiem (smołą) podczas prac izolacyjnych na dachu.", k: "Ugaszono kocioł z lepikiem przy użyciu proszku gaśniczego. Poszkodowany jeden dekarz - drobne oparzenia przedramienia, zaopatrzony na miejscu w KPP (hydrożele). Wezwijcie patrol by odebrać protokół powypadkowy.", locType: "building", pol: true },
  { t: "Zgłoszenie o bardzo gęstym, trującym dymie z komina warsztatu samochodowego. Prawdopodobnie właściciel spala przepracowany olej lub śmieci, smród dusi sąsiadów.", k: "Osoba spalająca materiały niedozwolone w piecu warsztatowym (plastiki i olej opałowy). Nakazano wygaszenie. W związku z naruszeniem ustawy wezwano patrol Policji w celu ukarania mandatem.", locType: "industrial", pol: true },
  { t: "Pożar lasu młodnika na sporym obszarze. Teren górzysty, bardzo trudny dojazd dla wozów pożarniczych. Ogień szybko się rozchodzi z dołu na górę.", k: "Pożar w młodniku na obszarze około 3 hektarów. Sprzęt mobilny nie dojeżdża, rozwijamy główną magistralę wodną (ok. 800m wężów W-75). Żądam natychmiastowego dysponowania Dromadera (samolotu gaśniczego) ze względu na wierzchołkowy charakter pożaru!", locType: "forest" },
  { t: "Huk i kule ognia z rozdzielni SN (średniego napięcia) (transformatora). Zabezpieczenia wystrzeliły w powietrze, stacja płonie.", k: "Pożar stacji transformatorowej wolnostojącej. Teren wygrodzono, odsunięto gapiów. Zastosowano gaśnice proszkowe 6kg dopiero po potwierdzeniu odłączenia prądu przez dyżurnego Pogotowia Energetycznego.", locType: "road" },
  { t: "Pożar paneli fotowoltaicznych na dachu hali sportowej szkoły podstawowej.", k: "Zlokalizowano pożar inwertera oraz trzech modułów PV. Odłączono rozłączniki DC/AC. Rozstawiono skokochron oraz sprawiono podnośnik. Użyto CO2 do gaszenia inwertera. Prowadzimy nadzór termowizyjny paneli.", locType: "public" },
  { t: "Na terenie złomowiska płonie potężna sterta wraków samochodowych.", k: "Silny, intensywny pożar aut na złomowisku. Płonie ok. 15 zdemontowanych wraków ułożonych w stos. Podajemy ciężką pianę, proszę zorganizować dostawę wody cysternami (SCCn). Informacja do WIOŚ ze względu na skażenie ujęcia wód.", locType: "industrial", pol: true }
];

export const mzScenarios = [
  { t: "Zderzenie czołowe dwóch samochodów osobowych przy dużej prędkości. Jeden pojazd dachował i wpadł do rowu. Widać osoby zakleszczone, jedna na pewno nieprzytomna.", k: "Rozpoznanie: Zdarzenie masowe typu w komunikacji drogowej. W pojeździe w rowie znajduje się jedna osoba zakleszczona, podjęto wykonanie dostępu przy użyciu sprzętu ratownictwa technicznego. Poszkodowany jest nieprzytomny - brak funkcji życiowych. Pilnie dysponujcie 2 ZRM i śmigłowiec LPR ratownik!", locType: "intersection", zrm: true, pol: true },
  { t: "Burza powaliła potężny stary dąb, który spadł prosto na jadący samochód dostawczy. Droga zablokowana.", k: "Zastano powalone drzewo na pojeździe typu bus. Kierowca na szczęście nie odniósł obrażeń (uciekł na siedzenie pasażera). Zablokowana DK. Przystępujemy do usuwania drzewa pilarkami łańcuchowymi. Ruch organizuje Policja.", locType: "road", pol: true },
  { t: "Z piwnicy w bloku wielorodzinnym śmierdzi silnie siarkowodorem lub jakimś gazem, kilku lokatorów narzeka na mdłości.", k: "Wprowadzono ratowników z ODO i miernikami wielogazowymi. Stwierdzono stężenie tlenku węgla (80 ppm) od wadliwie działającego piecyka gazowego. Zarządzono ewakuację klatki, pogotowie ratunkowe opatruje 2 podtrutych.", locType: "apartment", zrm: true },
  { t: "Trzy samochody wjechały w poślizg na plamie niezidentyfikowanej substancji (chyba oleju silnikowego) ciągnącej się na długości ok. 500 metrów.", k: "Potwierdzam ogromną plamę ropopochodną na jednym z pasów jezdni. Trzy auta uszkodzone w rowie, brak osób z ranami. Rozpoczęto neutralizację dyspergentem i zasypywanie sorbentem (sorpcja). Zajmie nam to ok. 2 godziny.", locType: "intersection", pol: true },
  { t: "Dziecko wcisnęło palce między ościeżnicę a szybę pancerną drzwi obrotowych w banku i nie można go wyciągnąć. Matka panikuje.", k: "Palec dziecka uwolniony przy pomocy rozpieracza ramieniowego (małego) i drewnianych klinów. Nie doszło do trwałego zmiażdżenia paliczków. Zespół pogotowia ratunkowego obecny na miejscu przejął poszkodowane dziecko.", locType: "public", zrm: true },
  { t: "Osoba zamknęła się w windzie, mechanizm zaciął się między 6 a 7 piętrem i z windy nie dochodzą głosy odpowiedzi.", k: "Uwolniono 75-letniego mężczyznę z windy przy użyciu ręcznego odryglowania hamulca w maszynowni, kabinę zjechano na piętro. Mężczyzna zasłabł z powodu stresu cieplnego. Podano tlen, czeka w rękach RTM z karetki.", locType: "apartment", zrm: true },
  { t: "Duże zwisające sople lodu nad głównym wejściem do przedszkola zagrażają wchodzącym z dziećmi rodzicom.", k: "Zadysponowano drabinę SCD-30. Usunięto zagrożenie (ok. 20 sopli lodowych oraz nawisy śnieżne z dachu przedszkola). Teren taśmowany. Interwencja zakończona, sprzęt wraca do koszar.", locType: "public" },
  { t: "Cysterna przewożąca amoniak zderzyła się z filarem wiaduktu. Przez uszkodzony zawór zrzutowy wydobywa się obłok białego, żrącego gazu. Widzę rannych świadków.", k: "Zdarzenie CBRNE! Sytuacja krytyczna. Substancja zidentyfikowana - Amoniak bezwodny. Chmura idzie w stronę osiedla mieszkaniowego, utworzono kurtynę wodną na drodze ucieczki. W strefie pracuje zastęp w ubraniach Chemoodpornych typ 1A (CUG). Ogłoście alarm i ewakuację strefy 500m wokół zdarzenia!", locType: "intersection", zrm: true, pol: true },
  { t: "Zgłoszenie od operatora koparki - podczas prac ziemnych na terenie budowy odkryto duży niewybuch (bombę lotniczą) prawdopodobnie z czasów 2WŚ.", k: "Potwierdzam znalezisko (niewybuch lotniczy dł. ok. 100 cm). Zarządzono ewakuację wszystkich pracowników budowy i mieszkańców 3 pobliskich domów na bezpieczną odległość (promień 300m). Oczekujemy na zabezpieczenie rejonu przez pododdziały Antyterrorystyczne Policji i saperów wojskowych.", locType: "building", pol: true },
  { t: "Zalana ulica i podziemny garaż po przejściu ekstremalnej ulewy z gradem. Woda sięga na metr, kilka aut zalanych całkowicie.", k: "Na miejscu liczne podtopienia, wypompowywanie wody z poziomu -1 trwa. Wprowadzono do garaży pompy szlamowe 2 szt. W autach nie stwierdzono uwięzionych osób. Droga dojazdowa na osiedle nadal jest nieprzejezdna.", locType: "road" },
  { t: "Rój agresywnych os zadomowił się na dachu szkoły podstawowej zaraz nad wejściem głównym. Rano użądlone zostało dziecko.", k: "Strażacy w ubraniach pszczelarskich zdjęli gniazdo i przetransportowali owady w bezpieczne miejsce (poza teren zabudowany). Odymiono wejście do szkoły w celu zdezorientowania resztek owadów.", locType: "public" },
  { t: "Rybak zgłasza, że na zamarzniętym jeziorze załamał się lód pod przechodniem kilkadziesiąt metrów od brzegu. Człowiek w wodzie!", k: "Uruchomiono deskę lodową i sanie. Ratownik dotarł do poszkodowanego zabezpieczonego linkami ratowniczymi i wydobył go na lód. Poszkodowany wychłodzony z oznakami hipotermii, przekazany przytomny do R-ki. Szybka akcja ratunkowa zakończona sukcesem.", locType: "forest", zrm: true },
  { t: "Osoba upadła w trakcie grzybobrania w lesie - podejrzenie złamania kości miednicy lub biodra, nie potrafi się ruszyć, pogotowie nie potrafi dojechać swoim autem.", k: "Poszkodowana zabrana i zabezpieczona na noszach typu deska, ułożona w wozie strażackim terenowym. Dowozimy ją około kilometra do najbliższej drogi utwardzonej, gdzie przejmuje pacjentkę załoga Karetki. Teren leśny jest bardzo podmokły.", locType: "forest", zrm: true },
  { t: "W sklepie chemicznym stłuczono kilka szklanych baniaków z silnym kwasem. Kasjerka ma oparzenia i duszności od oparów kwasu.", k: "Sklep wywietrzony. Pracujemy w maskach filtrujących P3. Rozsypujemy piasek kwarcowy i proszek wiążący (sorbent chemiczny) na żrący płyn. Kobieta jest obsługiwana tlenem do czasu dojazdu ambulansu.", locType: "commercial", zrm: true, pol: true },
  { t: "Czujnik czadu zgłasza zagrożenie - alarm. Od rana lokatorzy palili w kominku w salonie. Jedno dziecko ma nudności.", k: "Urządzenie pomiarowe PGM (Miernik Wielogazowy) wskazał 210 ppm tlenku węgla na 1 piętrze domu. Kominek został rozpalony przy braku odpowiedniego nawiewu - wsteczny ciąg kominowy. Wywietrzono w pełni parter budynku, zalecenia wystawione na piśmie.", locType: "building", zrm: true },
  { t: "Osoba chce skoczyć z dachu wysokiego budynku mieszkalnego (wieżowiec, 11 piętro). Negocjatorzy policyjni nie pomagają.", k: "Zabezpieczenie terenu z użyciem skokochronu rozstawionego pod miejscem potencjalnego upadku desperata. Brak możliwości rozłożenia drabiny na tę wysokość. Sprawę przejęli wykwalifikowani ratownicy psycholodzy policyjni. Pozostajemy na miejscu z ZRM.", locType: "building", pol: true, zrm: true },
  { t: "Rozlane paliwo przy stanowisku stacji benzynowej, około 50 litrów oleju napędowego po urwaniu pistoletu, wąż z uszkodzonego dystrybutora ciągle leje paliwo na bruk.", k: "Odłączono awaryjnie prąd na stacji i zakręcono zawór odcinający w systemie dystrybutorów paliw. Rota w pełnym wyposażeniu nakłada pianę gaśniczą (wytwornica pianowa), aby zabezpieczyć ulatniające się opary. Po akcji pokryliśmy miejsce grubą warstwą sorbentu.", locType: "commercial" },
  { t: "Kierujący uderzył bokiem we wiatę autobusową i słup sygnalizacji świetlnej, konstrukcja grozi zawaleniem na pas jezdni.", k: "Osoba kierująca doznała urazów wielonarządowych i znajduje się na Czerwonej Taśmie Triage. Wiatę zabezpieczyliśmy stemplami i taśmą grodzeniową, czekamy na przyjazd służb porządkowych ZDM (zarządu miejskich dróg) aby usunęli słup i uszkodzoną sygnalizację.", locType: "intersection", zrm: true, pol: true },
  { t: "Pożar w maszynowni wyciągu narciarskiego. Kolejka z krzesełkami stanęła. Uwięzionych kilkunastu narciarzy w powietrzu, krzyczą na mrozie.", k: "Działania dwutorowe: Jedna rota likwiduje pożar silnika wyciągu, z kolei Pluton Ratownictwa Wysokościowego PPN przystępuje do czasochłonnej linowej ewakuacji narciarzy bezpośrednio z poszczególnych krzesełek w dół. Zaangażowanych łącznie ok. 14 ratowników. Trudna, specjalistyczna akcja techniczna.", locType: "forest", zrm: true },
  { t: "Samochód dostawczy przewożący sprzęt AGD zapalił się w długim tunelu drogowym pod miastem. Pełno gęstego czarnego dymu, systemy wentylacyjne tunelu walczą.", k: "Potężne zadymienie tunelu na długości ok. 2 kilometrów. Zespół rot przystępuje do poszukiwań pieszych, którzy opuścili uszkodzone auta stojące w korku w tunelu. Ugasiliśmy usterkę przedziału ładunkowego dostawczaka pianą ciężką w 15 minut. ZRM zabezpiecza wyprowadzonych przed wejściem tunelu.", locType: "road", zrm: true, pol: true }
];

export const afScenarios = [
  { t: "Czujka na 5. piętrze biurowca włączyła sygnał pożarowy w Centrum Operacyjnym Bezpieczeństwa, załączyły się syreny SSP.", k: "Alarm z czujnika jonizacyjnego (Nr. 511-A), na miejscu nie stwierdzono zadymienia ani pożaru. Powodem uruchomienia detektora okazało się prowadzonych nielegalnych prac remontowych ze szlifierką (pył po cięciu gładzi uszkodził czujkę). System został wyłączony w stan czuwania. Zdarzenie jako Fałszywy.", locType: "commercial", reportedType: "pozar" },
  { t: "Kobieta dzwoni w panice, twierdzi, że z okna sąsiedniego bloku widzi gigantyczny płomień pożarowy połączony z łuną iskier.", k: "Udaliśmy się we wskazaną klatkę i piętro. Mieszkańcy zaskoczeni obecnością JRG – powodem wizualizacji pożaru był 70-calowy telewizor, w którym rodzina odtwarzała nagranie pętli z pieca kominkowego w 4K UltraHD, w świetle wyłączonych żarówek w mieszkaniu. System zaklasyfikował wyjazd jako ALARM W DOBREJ WIERZE.", locType: "apartment", reportedType: "pozar" },
  { t: "Dziecięcy, spanikowany głos informuje: 'szkoła się cała pali z dachem, są zabici' – następnie połączenie zrywa.", k: "Kolejny chuligański wybryk. Szkoła nie nosi znaków dymu. Potwierdzono u dyrekcji: wszystkie alarmowe stacje są nieuruchomione. Sporządzono krótki raport dla Policji, posłuży w poszukiwaniu anonima dzowniącego przez zablokowany telefon.", locType: "public", pol: true, reportedType: "pozar" },
  { t: "Monitoring ochrony z hal produkcyjnych donosi przez aplikację, że kamera termowizyjna uchwyciła bardzo nagłą zmianę temperatury. Zgłaszają jako ryzyko zapłonu w strefie.", k: "Sprawdzono obiekt hal. Okazało się, że nowa rura C.O. uległa awarii i wystrzeliła ze złączki pod wpływem pary do góry – co na widoku z termo dało efekt potężnego i gorącego 'płomienia' i zadymienia w wizji maszyny. Został wezwany Serwis Konserwatorski obiektu do usterki wodnej. Powrót JRG.", locType: "industrial", reportedType: "pozar" },
  { t: "Sąsiedzi zgłaszają niezwykle silny i obrzydliwy odór padliny na korytarzu obok drzwi numer 15. Brak wejścia od paru dni do lokalu.", k: "Drzwi siłowo sforsowano w obawie o zwłoki we wnętrzu mieszkania. Lokal pusto, bez ludzkiego zgonu. Znaleziono jednak uszkodzoną, gigantyczną zamrażarkę wypełnioną starym i gnijącym mięsem, z powodu braku zasilania po burzy. Alarm przekazano na Sanepid, nie interweniujemy dalej.", locType: "apartment", pol: true, reportedType: "mz" },
  { t: "System automatyczny w pojeździe (eCall) wysłał do WCPR koordynaty z komunikatem Ostrego Wypadku oraz Rolowania (dachowania) auta z utratą funkcji życiowych kierowcy.", k: "Rozpoznaliśmy zgłoszenie eCall w szczerym lesie blisko stawu. To auto jest zdemolowane, stało od kilku lat, ale podczas nieudanej zabawy młodzieży polegającej na spychaniu zardzewiałej karoserii w przepaść z załadowanym wewnątrz akumulatorem - eCall samoczynnie wystrzelił alarm SOS na policję. Brak żywych ludzi i konieczności interwencji RTM. Powiadomiono KPP.", locType: "forest", pol: true, reportedType: "mz" },
  { t: "Przechodzień dzwoni, widzi kłęby gryzącego, chemicznego dymu wychodzące ze studni i kratki wentylacyjnej przy skrzyżowaniu (może to instalacja kable?).", k: "Dojazd w KDR bezproblemowy - po sprawdzeniu kamerą termowizyjną i miernikami wykluczono pożar pod ziemią. Sytuacja wynikała ze specyficznej instalacji MPEC (ciepło technologiczne z magistrali sieci C.O. na skrzyżowaniu wyrzuciło do atmosfery ciepłą parę wodną o zapachu wilgoci). Tzw. Fałszywy Alarm w dobrej wierze.", locType: "intersection", reportedType: "pozar" },
  { t: "Wciśnięto Ręczny Ostrzegacz Pożarowy ROP na hali w markecie. Automatyczne oddymianie i okna sufitowe na pasażu zadziałały awaryjnie na full mocy.", k: "Ktoś użył przycisku ROP dla popisu i by włączyć stacje sygnalizujące i uciec ze sklepu. Ochrona szuka nieznanej młodzieży sprawdzając miejski i sieciowy monitoring kamer z pasażu OBI. Pasażerom zezwolono na dalsze zakupy. Zresetowano tablicę złącz.", locType: "commercial", pol: true, reportedType: "pozar" },
  { t: "W przedszkolu, od rana dzwoni piszcząc i trzeszcząc stara, głośna czujka alarmowa na szatni do wykrywania dymu CO. Mamy strach przed trującym czadem i tlenkiem węgla u dzieci na dole.", k: "Interwencja błyskawiczna ze względu na budynek użyteczności szkół publicznych (Przedszkola) i ewentualnych dziecięcych Młodocianych w środku. Strażacy po badaniach miernikami nie wykrywają ani procenta śmiertelnych gazów ulatniających. Stwierdza się za to kompletnie wyczerpaną instalację na wymianę akumulatorów. Stara czujka informowała głośno w piskach, by zrobiono jej niezbędny serwis po 2 latach spania w szafce od kurzu.", locType: "public", reportedType: "mz" },
  { t: "Telefon w którym słychać jak starsza Pani histeryzuje, że jej kot zszedł ze schodów balkonowych ale utkwił nogą w barierki poręczy wejściowej obok parteru.", k: "Młody Strażak z rotą załatwił w kilka minut rozchylanie stalowego trzpienia na siłę (lekko użyto wyważarki halligan-tool od sprzętu zręcznościowego). Nie było tu skomplikowanej wzniosłej akcji, kocię biega dalej zdrowe, uradowana starsza emerytka. Powrót bez trąb sygnałowych.", locType: "building", reportedType: "mz" }
];
