export const pozScenarios = [
  { t: "Pali się altanka na ogródkach działkowych, ogień przenosi się na drzewa.", k: "Altanka w całości objęta pożarem. Podajemy dwa prądy wody w natarciu i jeden w obronie na drzewa." },
  { t: "Widzę silny ogień i czarny dym z okna na 3. piętrze bloku mieszkalnego. Ktoś wzywa pomoc z balkonu!", k: "Pożar w fazie rozwiniętej na 3 piętrze. Osoba na balkonie. Proszę o drabinę mechaniczną oraz ZRM dla poszkodowanego!", zrm: true, pol: true },
  { t: "Pali się auto osobowe na poboczu drogi, ogień objął całą komorę silnika.", k: "Samochód całkowicie w ogniu. Podajemy pianę ciężką. Proszę o patrol Policji do zabezpieczenia ruchu.", pol: true },
  { t: "Sadza pali się w przewodzie kominowym domu jednorodzinnego, lecą iskry i słychać huk.", k: "Potwierdzam pożar sadzy. Rozstawiamy sprzęt kominiarski. Proszę o dodatkową kamerę termowizyjną." },
  { t: "Pożar trawy na nieużytkach. Ogień niebezpiecznie zbliża się do pobliskiego lasu i zabudowań.", k: "Duży pożar traw, silny wiatr. Proszę o zadysponowanie kolejnych 2 wozów GBA w celu obrony zabudowań." },
  { t: "Zgłoszenie z monitoringu ppoż. Pożar w hali magazynowej, pracownicy ewakuują się.", k: "Sytuacja poważna, gęsty dym w hali. Trwa ewakuacja. Prosimy o kolejne siły i ODO!" },
  { t: "Dym wydobywa się ze śmietnika podziemnego na osiedlu.", k: "Zwykły pożar śmietnika. Podajemy jeden prąd wody. Sytuacja opanowana." },
  { t: "Wybuch gazu w kamienicy, pożar na piętrze, zawalona część ściany nośnej.", k: "Katastrofa budowlana! Kamienica częściowo zawalona. Wiele ofiar. Proszę o SGRW, 4 x ZRM i Policję!", zrm: true, pol: true },
  { t: "Pali się dach opuszczonego budynku gospodarczego.", k: "Płonie dach pustostanu. Brak osób wewnątrz. Podajemy prądy wody z drabiny." },
  { t: "Zwarcie w rozdzielni elektrycznej w piwnicy wielkiej płyty, cała klatka schodowa w gęstym, gryzącym dymie.", k: "Pożar rozdzielni w piwnicy. Odcięto prąd. Przewietrzamy klatkę schodową, lokatorzy zostają w domach." },
  { t: "Pali się opona w ciężarówce na autostradzie A4. Kierowca zjechał na pas awaryjny.", k: "Pożar naczepy ugaszony. Policja na miejscu steruje ruchem.", pol: true },
  { t: "Pożar mieszkania na parterze. Starsza osoba najprawdopodobniej została w środku.", k: "Osoba ewakuowana, nieprzytomna, RKO. Pilnie prosimy o ZRM!", zrm: true },
  { t: "Ogień na dachu stacji benzynowej w rejonie dystrybutorów!", k: "Sytuacja bardzo niebezpieczna, pożar w okolicach dystrybutorów. Odcięto zawory bezpieczeństwa. Podajemy pianę." },
  { t: "Pożar śmieci na balkonie na 6. piętrze. Spada płonący plastik na niższe piętra.", k: "Ugasiśmy balkon z roty zewnętrznej (SHD). Rozpoznanie mieszkań poniżej w toku." },
  { t: "Płonie stolarnia, ogień wychodzi na zewnątrz przez świetliki w dachu. Brak osób wewnątrz.", k: "Pożar rozwinięty warsztatu. Duże zadymienie. Proszę o 2 kolejne zastępy z aparatami ODO." },
  { t: "Pożar lasu w okolicy leśniczówki. Płonie poszycie na powierzchni około 50 arów.", k: "Sytuacja opanowana. Wymagane dodatkowe tłumice, oblewamy obrzeża pożarzyska." },
  { t: "Zapalił się stóg siana na polu. Silny wiatr rozprzestrzenia ogień.", k: "Płonie stóg. Nie ma zagrożenia dla budynków. Zaczynamy przerzucanie widłami." },
  { t: "Dym i płomienie w warsztacie samochodowym. Wewnątrz znajdują się butle z gazem technicznym i acetonem.", k: "Ewakuowaliśmy 3 butle z acetylenem, aktualnie je chłodzimy! Pożar warsztatu powoli opanowywany." },
  { t: "Kłęby dymu nad halą recyklingu tworzyw sztucznych. Pożar wewnątrz hali sortowni.", k: "Trwa gaszenie pożaru tworzyw sztucznych wewnątrz sortowni. Widoczność zerowa. Wysłano 2 roty ODO." },
  { t: "Zgłoszono pożar transformatora na osiedlu. Słychać było głośny huk, a teraz iskrzy się i płonie olej.", k: "Zabezpieczamy teren, czekamy na Pogotowie Energetyczne w celu wyłączenia napięcia! Nie lejemy wody!" },
  { t: "Płonie drewniana konstrukcja dachu budowanego kościoła. Ogień jest bardzo duży, widoczny z kilku kilometrów.", k: "Dach objęty pożarem. Potrzebne cysterny z wodą i kolejne drabiny!" },
  { t: "Podczas jazdy zapalił się autobus miejski. Pasażerowie zostali ewakuowani, autobus jest cały w ogniu.", k: "Autobus wypalony doszczętnie. Brak poszkodowanych. Zamknięto ulicę, prosimy o Policję do objazdów.", pol: true },
  { t: "Pali się garaż blaszany. Wewnątrz stoi motocykl i kanistry z paliwem.", k: "Garaż opanowany. Spalony jeden motocykl, wynieśliśmy stopione kanistry z benzyną." },
  { t: "Pożar pustostanu, widoczny ogień w oknach na pierwszym piętrze. Często przebywają tam osoby bezdomne.", k: "Zlokalizowaliśmy dwójkę bezdomnych, ulegli zatruciu dymem. Proszę o dwa ZRM!", zrm: true, pol: true },
  { t: "Pożar hali magazynowej z materiałami chemicznymi. Ogień szybko się rozprzestrzenia, słychać wybuchy beczek.", k: "Proszę o SGRChem i pluton gaśniczy. Zasięg pożaru jest ogromny!" },
  { t: "Zgłoszenie o pożarze w szpitalu na oddziale ratunkowym. Gęsty dym na korytarzach, trwa gorączkowa ewakuacja.", k: "Częściowa ewakuacja szpitala. Ogień zlokalizowany w serwerowni. Brak osób poszkodowanych." },
  { t: "Pożar w centrum handlowym. Ogień na food courcie. Setki ludzi ucieka do wyjść ewakuacyjnych.", k: "Sytuacja bardzo chaotyczna. Ugasiliśmy pożar frytownicy. Ludzie spanikowali. Proszę o Policję do zabezpieczenia tłumu.", pol: true },
  { t: "Pali się podziemny parking pod apartamentowcem. Słychać strzały opon, dym wchodzi na klatki schodowe.", k: "Spalono 3 samochody na poziomie -2. Duże zadymienie w pionach. Wentylujemy klatki." },
  { t: "Wybuch pyłu w zakładzie drzewnym (tartaku). Płonie główna hala, zniszczony dach, prawdopodobnie są poszkodowani.", k: "Potwierdzam wybuch, jedna osoba ciężko poparzona. Wysyłajcie ZRM i LPR!", zrm: true },
  { t: "Pożar składowiska opon i gabarytów na wysypisku śmieci. Czarny słup dymu widoczny z 10 kilometrów.", k: "Ogień rozprzestrzenił się na hałdzie opon. Proszę o ciężki sprzęt gaśniczy i informację do Ochrony Środowiska." }
];

export const mzScenarios = [
  { t: "Zderzenie dwóch samochodów osobowych, jedna osoba zakleszczona w pojeździe, płyny na jezdni.", k: "Osoba zakleszczona uwalniana narzędziami hydraulicznymi. ZRM już przejmuje poszkodowanego.", zrm: true, pol: true },
  { t: "Wiatr powalił duże drzewo na jezdnię, droga jest całkowicie zablokowana. Drzewo zerwało też linię energetyczną.", k: "Zabezpieczamy zerwaną linię. Oczekujemy na Pogotowie Energetyczne. Drzewo pocięte." },
  { t: "W mieszkaniu starsza pani zasłabła i nie otwiera drzwi, słychać wołanie o pomoc.", k: "Otworzono drzwi sprzętem burzącym. Kobieta przytomna. ZRM udziela MCR.", zrm: true },
  { t: "Czuć silną woń gazu na klatce schodowej w bloku czteropiętrowym.", k: "Mierniki wykazują duże stężenie DGW. Rozpoczynamy ewakuację klatki. Proszę o Pogotowie Gazowe i Policję.", pol: true },
  { t: "Duża plama oleju na jezdni na skrzyżowaniu, auta wpadają w poślizg. Plama ciągnie się przez kilkaset metrów.", k: "Posypujemy plamę sorbentem. Zajmie to trochę czasu. Prosimy o Policję do wstrzymania ruchu.", pol: true },
  { t: "Zatrzaśnięte roczne dziecko w nagrzanym samochodzie na parkingu pod galerią.", k: "Wybito szybę, dziecko wyciągnięte. Profilaktycznie wezwijcie ZRM dla malucha.", zrm: true, pol: true },
  { t: "Osoba uwięziona w zaciętej windzie od 40 minut. Zaczyna brakować jej powietrza (atak paniki).", k: "Dźwig otwarty, osoba bezpieczna. Brak konieczności wezwania ZRM." },
  { t: "Dachówka zwisa z krawędzi dachu kamienicy i zagraża przechodniom na chodniku.", k: "Dachówki usunięte z kosza podnośnika. Teren zabezpieczony. Koniec działań." },
  { t: "Samochód zjechał z drogi i uderzył w przepust. Kierowca jest nieprzytomny.", k: "Wyciągamy nieprzytomnego kierowcę. Pilnie ZRM! Ruch zablokowany, powiadomcie drogówkę.", zrm: true, pol: true },
  { t: "Rozlano nieznaną substancję chemiczną w laboratorium szkolnym. Dwie osoby uskarżają się na ból głowy.", k: "Ewakuowano szkołę. Zabezpieczamy substancję roztworem neutralizującym. Poszkodowani w ZRM.", zrm: true, pol: true },
  { t: "Kot utknął na czubku bardzo wysokiej brzozy i głośno miauczy od dwóch dni.", k: "Kot zdjęty i przekazany właścicielce. Sytuacja opanowana." },
  { t: "Zalana piwnica w budynku mieszkalnym po gwałtownej ulewie. Woda sięga pół metra.", k: "Rozpoczynamy pompowanie szlamówkami. Wody sukcesywnie ubywa." },
  { t: "Zderzenie motocykla z samochodem dostawczym. Motocyklista leży na jezdni, brak funkcji życiowych - CPR rozpoczęte.", k: "Ciężki wypadek motocyklisty! Prowadzimy ciągłe RKO! ZRM i LPR w trybie pilnym!!", zrm: true, pol: true },
  { t: "Czujnik tlenku węgla (czadu) załączył się w łazience z piecykiem gazowym. Mieszkańcy skarżą się na zawroty głowy.", k: "Czujniki potwierdzają stężenie CO. Ewakuowaliśmy rodzinę, przekazano do ZRM.", zrm: true },
  { t: "Gniazdo szerszeni bezpośrednio nad oknem przedszkola.", k: "Owady zebrane do worka z użyciem roju. Przedszkole bezpieczne." },
  { t: "Osoba poślizgnęła się na nasypie przy rzece i nie może samodzielnie wyjść po stromym zboczu ze złamaną nogą.", k: "Osobę ewakuowano z użyciem lin i noszy kubełkowych. Przekazano zespołowi ratownictwa.", zrm: true },
  { t: "Podejrzana walizka na przystanku autobusowym, brak właściciela od 2 godzin. Ewakuowano najbliższy teren.", k: "Zabezpieczamy rejon. Czekamy na pirotechników z Policji. ZRM w zabezpieczeniu.", zrm: true, pol: true },
  { t: "Rozszczelnienie rurociągu z amoniakiem w zakładzie produkcyjnym. Gęsta mgła chemiczna wokół hali. Wewnątrz zostały 3 osoby.", k: "Zakładamy ubrania ciężkie gazoszczelne. Ratownicy wchodzą do strefy szukać poszkodowanych. SGRChem potrzebny!", zrm: true, pol: true },
  { t: "Kolejka górska zacięła się na wysokości 20 metrów. W wagonikach znajdują się uwięzione osoby, jedna ma atak paniki.", k: "Ewakuujemy ludzi z użyciem SGRW (wysokościówki). ZRM zabezpiecza ewakuowanych na dole.", zrm: true },
  { t: "Mężczyzna grozi skokiem z mostu do rzeki. Na miejscu obecna jest już policja, która prosi o zabezpieczenie skoku (skokochron/łódź).", k: "Rozstawiono skokochron i zwodowano łódkę na rzece. Negocjatorzy policyjni w akcji.", pol: true, zrm: true },
  { t: "Zawalenie się ściany podczas prac rozbiórkowych. Pod gruzami znajduje się jeden z robotników. Brak z nim kontaktu.", k: "Odkopujemy gruzy ręcznie i przy pomocy sprzętu. Proszę o psy poszukiwawcze SGRP i ZRM!", zrm: true, pol: true },
  { t: "Rój pszczół osiadł na przejściu dla pieszych przy ruchliwej ulicy, zagraża przechodniom.", k: "Pszczoły zebrane do rojnicy i przekazane zaprzyjaźnionemu pszczelarzowi." },
  { t: "Zalane tory tramwajowe po oberwaniu chmury, woda dostaje się do okolicznych sklepów. Podtopionych kilkanaście piwnic.", k: "Brak zagrożenia życia. Pompy powoli odbierają wodę. Akcja potrwa kilka godzin." },
  { t: "Wypadek autokaru turystycznego na zjeździe z autostrady. Autokar leży na boku, wewnątrz ok. 40 osób. Zdarzenie Masowe!", k: "Zdarzenie masowe! Wdrażamy Triage! Na miejsce potrzebujemy jak najwięcej karetek ZRM i LPR!", zrm: true, pol: true },
  { t: "Woda podmyła wał przeciwpowodziowy, istnieje ryzyko przerwania i zalania kilku posesji. Potrzebne worki z piaskiem.", k: "Układamy wał z worków z piaskiem by zniwelować podsiąki. Sytuacja pod kontrolą." },
  { t: "Samochód osobowy wpadł do stawu hodowlanego, powoli tonie. Kierowca wewnątrz walczy z drzwiami, auto zanurza się.", k: "Kierowca wyciągnięty przez ratowników w skafandrach lodowych! RKO! Potrzebny ZRM!", zrm: true, pol: true },
  { t: "Rozszczelniona cysterna kolejowa z kwasem siarkowym na bocznicy. Wyciek jest intensywny, chmura gazu idzie na pobliskie osiedle.", k: "Tworzymy kurtyny wodne, by strącać gaz! Wzywajcie pluton SGRChem!", pol: true },
  { t: "Wypadek awionetki podczas podchodzenia do lądowania. Samolot spadł na las obok lotniska aeroklubu. Brak kontaktu z pilotem.", k: "Samolot płonie, uwięziony pilot wewnątrz. Podajemy pianę i przystępujemy do wydobycia. LPR i Policja wymagane!", zrm: true, pol: true },
  { t: "Awaria zasilania w szpitalu. Agregat prądotwórczy nie odpalił. Respirator na OIOM działa na baterii, która zaraz się rozładuje.", k: "Podpinamy szpital pod nasz agregat prądotwórczy dużej mocy. Zasilanie OIOM przywrócone." }
];

export const afScenarios = [
  { t: "Czujka pożarowa SAP wyje w budynku biurowym, brak widocznych oznak pożaru z zewnątrz.", k: "Potwierdzamy fałszywy alarm z monitoringu. Usterka czujki na poziomie 1." },
  { t: "Zgłoszenie o dymie w lesie, ale to chyba ognisko lub grill u sąsiada na ogródku.", k: "Dym pochodził z legalnie rozpalonego grilla na posesji. Brak zagrożenia." },
  { t: "Ktoś dzwoni i mówi, że szkoła się pali, po czym po prostu się rozłącza (dziecięcy głos).", k: "Złośliwy alarm fałszywy - żart dziecka. Przekazuję informację na Policję do ustalenia sprawcy.", pol: true },
  { t: "Zgłoszenie pożaru w fabryce, ale ochrona obiektu niczego nie potwierdza.", k: "Zjawisko optyczne - para wodna z komina widziana pod słońce. Alarm w dobrej wierze." },
  { t: "Pani zgłasza nieprzyjemny zapach gazu, jednak po przyjeździe okazuje się to zapachem gotowanej kapusty.", k: "Sprawdzono miernikami całą klatkę. To zapach z gotowania u sąsiada." },
  { t: "Wciśnięty Ręczny Ostrzegacz Pożarowy (ROP) w galerii handlowej bez powodu przez nieznanego sprawcę.", k: "ROP zbity złośliwie. Sprawę przejmuje ochrona centrum." },
  { t: "Sygnał uaktywnionej czujki tlenku węgla. Przyczyną okazuje się niski stan baterii (sygnał rozładowania).", k: "Brak stężenia CO. Użytkownicy muszą wymienić baterię w urządzeniu." },
  { t: "Sąsiad zgłasza dziwne błyski w sąsiednim mieszkaniu. To nowa instalacja LED choinki świątecznej.", k: "Alarm w dobrej wierze. To tylko światła na choince, które agresywnie migały." },
  { t: "Przechodzień melduje o parze ulatniającej się ze studzienki ciepłowniczej, myśląc że to dym pożarowy.", k: "To para technologiczna, brak zadymienia, fałszywy alarm w dobrej wierze." },
  { t: "Fałszywe powiadomienie systemu eCall z samochodu. Pojazd był tylko mocniej uderzony drzwiami na parkingu.", k: "System eCall uruchomiony przypadkowo na postoju. Brak poszkodowanych." }
];
